name: Dagger Check 

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run Check
        uses: dagger/checks@64525befa1c36dd55577dae083df5c8968d9325a #v1.1.0

    

