name: E2E Smoke Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

jobs:
  e2e_smoke:
    name: e2e_smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run E2E Tests
        uses: dagger/dagger-for-github@496f1b3d8b0d823834c13e67cf8a8e08ca3b9602 # v8.4.0
        with:
          version: "latest"
          verb: call
          args: e-2-e-tests --smoke=true --output=./playwright-results

      - name: Upload Test Reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4
        if: failure() 
        with:
          name: playwright-reports
          path: ./playwright-reports
          retention-days: 30


